[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "csv-helper"
version = "0.0.1"
authors = [{ name = "Andrew Tiu", email = "andrew.tiu88@gmail.com" }]
description = "A simple CLI for working with CSV data"
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
classifiers = ["Programming Language :: Python :: 3"]
dependencies = ["typer>=0.12.3", "polars>=0.20.29", "numpy"]

[project.scripts]
csv-helper = "csv-helper.main:app"

[project.urls]
Homepage = "https://github.com/winter-again/csv-helper"
Issues = "https://github.com/winter-again/csv-helper/issues"
